### ISSUE TITLE
Create Search component

### ISSUE THREAD

**Issue by solomiia-sahala** [solomiia-sahala/CoKeeper#14]
### Acceptance criteria's:
User is able to see Search field with the next items inside: 

- placeholder "Search the contact";

Depending to the media query (see *SRS "Design", width of input field and color of placeholder will be changed (see *Figma design).

Depending to the media query "screen", for desktop view the search will be displayed below header and for mobile view will be placed on the header. (see *Figma design,  *SRS "Design").
### Estimation: 2h

**Links:**
Figma design - [Figma](https://www.figma.com/file/J5Syu1z6LPJhIQdScukaa3/CoKeeper?node-id=0%3A1)
SRS - [SRS](https://docs.google.com/document/d/1Z0ceG_NtqwGXs6xRjqq8hb9AoqWj1lLzboL5epCSfkQ/edit#)

**Comment by alexandrbig** [comment]
What is the media query? 
Is it convenient for you to jump to another resource to get needed information?

**Comment by solomiia-sahala** [comment]
> What is the media query?
> Is it convenient for you to jump to another resource to get needed information?

Media query  is a CSS technique and it uses the @media rule to include a block of CSS properties only if a certain condition is true, in our case condition depends from the width of the screen. More detail Information about breakpoint is written in SRS "Design" (link is attached in description).
Do you recommend to place search component below the header for mobile and desktop view as well, so it will not confuse user?

**Comment by alexandrbig** [comment]
1. what is media query it is clear, but is it not clear which media query rule should be used to change the location of the search.
2. I mean not to change the position of the component. Sometimes one or two additional sentences can replace the whole document. It is clear for the customer/qa/developer.
We can keep such descriptions as they are for now. 
Let's see the implementation.

**Comment by solomiia-sahala** [comment]
added type of media query and more detail info about "Search" placement. Thanks.
