### ISSUE TITLE
Create New contact button

### ISSUE THREAD

**Issue by solomiia-sahala** [solomiia-sahala/CoKeeper#15]
### Acceptance criteria's:
User is able too see New contact button (see *Figma design)

User is able to click on the button and be redirected to the "New contact" page (will be implemented in the separate task).

Depending to the media query (see *SRS "Design", view of the button  will be changed. 
For desktop view: the button "New contact" is placed in header (see *Figma design). 
For the mobile the button "New contact" is placed below of the screen, between icons "Home" and "Favorites" (see *Figma design).

### Estimation: 1h

**Links:**
Figma design - [Figma](https://www.figma.com/file/J5Syu1z6LPJhIQdScukaa3/CoKeeper?node-id=0%3A1)
SRS - [SRS](https://docs.google.com/document/d/1Z0ceG_NtqwGXs6xRjqq8hb9AoqWj1lLzboL5epCSfkQ/edit#)

**Comment by alexandrbig** [comment]
> Depending to the media query (see *SRS "Design", view of the button will be changed (see *Figma design).

What if the design changed after you have developed the story?

**Comment by solomiia-sahala** [comment]
> > Depending to the media query (see *SRS "Design", view of the button will be changed (see *Figma design).
> 
> What if the design changed after you have developed the story?
I added more detail description about view of the button on the mobile and desktop views, so if the design will changed, we will be able to understand that this task was done according to the old design. Is it ok?
